tosca_definitions_version: ${alien4cloud.dsl.version}

template_name: yorc-kubernetes-types
template_author: Yorc
template_version: ${yorc.k8s.types.version}


# Note: If we reference a dependency using project.version then this component should
#       be versioned as project.version too otherwise we will have issues on snapshots
#       versions (our type not snapshot referencing a snapshot version)
imports:
  - org.alien4cloud.kubernetes.api:${alien4cloud.kubernetes.api.version}

artifact_types:
  yorc.artifacts.Deployment.Kubernetes:
    description: Docker deployment descriptor
    derived_from: tosca.artifacts.Deployment

node_types:
  yorc.nodes.kubernetes.api.types.DeploymentResource:
    derived_from: org.alien4cloud.kubernetes.api.types.DeploymentResource

  yorc.nodes.kubernetes.api.types.JobResource:
    derived_from: org.alien4cloud.kubernetes.api.types.JobResource

  yorc.nodes.kubernetes.api.types.StatefulSetResource:
    derived_from: org.alien4cloud.kubernetes.api.types.StatefulSetResource

  yorc.nodes.kubernetes.api.types.ServiceResource:
    derived_from: org.alien4cloud.kubernetes.api.types.ServiceResource

  yorc.nodes.kubernetes.api.types.SimpleResource:
    derived_from: org.alien4cloud.kubernetes.api.types.SimpleResource
