id: alien4cloud-yorc-provider
name: Yorc Orchestrator Provider
version: ${project.version}
description: >
  Plugin for Yorc Orchestrator.
configuration_class: alien4cloud.paas.yorc.YorcPluginConfiguration
component_descriptors:
  - bean_name: yorc-orchestrator-factory
    name: Yorc Orchestrator
    description: >
      Alien Plugin for Yorc
  - bean_name: yorc-kubernetes-modifier
    name: Yorc Modifier for Kubernetes
    description: >
      Yorc Modifier for Kubernetes
  - bean_name: yorc-openstack-server-group-modifier
    name: Openstack modifier for Server Group affinity and anti-affinity policies
    description: Openstack modifier for Server Group affinity and anti-affinity policies
  - bean_name: yorc-monitoring-modifier
    name: Yorc modifier for handling monitoring policies
    description: Yorc modifier for handling monitoring policies
  - bean_name: docker-to-singularity-modifier
    name: Yorc modifier for transforming Docker Jobs into Singularity/Slurm Jobs
    description: Yorc modifier for transforming Docker Jobs into Singularity/Slurm Jobs
  - bean_name: gangja-resolver-modifier
    name: Gangja config file resolver modifier
    description: A modifier that help resolve variables when a node connects to to static endpoints and has Gangja config file artefacts
dependencies:
  - alien4cloud-kubernetes-plugin
