package alien4cloud.paas.yorc.context.service.fsm;

import java.util.EnumSet;

import javax.inject.Inject;

import org.springframework.statemachine.StateMachine;
import org.springframework.statemachine.config.StateMachineBuilder;
import org.springframework.statemachine.config.builders.StateMachineConfigurationConfigurer;
import org.springframework.statemachine.config.builders.StateMachineStateConfigurer;
import org.springframework.statemachine.config.builders.StateMachineTransitionConfigurer;
import org.springframework.stereotype.Service;

/**
 * Finite State Machine builder
 * This class consists of the transition graph and a builder
 */
@Service
public class FsmBuilder {

	@Inject
	private FsmActions actions;

	protected StateMachine<FsmStates, FsmEvents> createFsm(String id, FsmStates initialState) throws Exception {
		StateMachineBuilder.Builder<FsmStates, FsmEvents> builder = StateMachineBuilder.builder();
		configure(builder.configureStates(), initialState);
		configure(builder.configureTransitions());
		configure(builder.configureConfiguration(), id);
		return builder.build();
	}

	private void configure(StateMachineStateConfigurer<FsmStates, FsmEvents> states,
			FsmStates initialState) throws Exception {
		states.withStates()
			.initial(initialState)
			.states(EnumSet.allOf(FsmStates.class));
	}

	private void configure(StateMachineTransitionConfigurer<FsmStates, FsmEvents> transitions)
			throws Exception {
		transitions
			.withExternal()
			.source(FsmStates.UNDEPLOYED).target(FsmStates.DEPLOYMENT_INIT)
			.event(FsmEvents.DEPLOYMENT_STARTED)
			.action(actions.buildAndSendZip())
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_INIT).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.DEPLOYMENT_CONFLICT)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_INIT).target(FsmStates.FAILED)
			.event(FsmEvents.FAILURE)
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_INIT).target(FsmStates.UNKOWN)
			.event(FsmEvents.GATEWAY_TIMEOUT)
		.and()
			.withExternal()
			.source(FsmStates.UNKOWN).target(FsmStates.DEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.DEPLOYMENT_IN_PROGRESS)
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_INIT).target(FsmStates.DEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.DEPLOYMENT_IN_PROGRESS)
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_IN_PROGRESS).target(FsmStates.DEPLOYED)
			.event(FsmEvents.DEPLOYMENT_SUCCESS)
			.action(actions.forceRefreshAttributes())
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_IN_PROGRESS).target(FsmStates.FAILED)
			.event(FsmEvents.FAILURE)

// Update stuff here
// Allow update from DEPLOYED state
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYED).target(FsmStates.UPDATE_IN_PROGRESS)
			.event(FsmEvents.UPDATE_STARTED)
			.action(actions.preUpdate())
// Allow update from UPDATED state
		.and()
			.withExternal()
			.source(FsmStates.UPDATED).target(FsmStates.UPDATE_IN_PROGRESS)
			.event(FsmEvents.UPDATE_STARTED)
			.action(actions.preUpdate())
// Allow update from UPDATE_FAILED state
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_FAILED).target(FsmStates.UPDATE_IN_PROGRESS)
			.event(FsmEvents.UPDATE_STARTED)
			.action(actions.preUpdate())
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_IN_PROGRESS).target(FsmStates.PRE_UPDATE_IN_PROGRESS)
			.event(FsmEvents.PRE_UPDATE_STARTED)
		.and()
			.withExternal()
			.source(FsmStates.PRE_UPDATE_IN_PROGRESS).target(FsmStates.PRE_UPDATE_IN_PROGRESS)
			.event(FsmEvents.PRE_UPDATE_RUNNING)
		// pre_update can be cancelled manually
		.and()
			.withExternal()
			.source(FsmStates.PRE_UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_FAILED)
			.event(FsmEvents.PRE_UPDATE_CANCELED)
			.action(actions.notifyPrePostUpdateFailure())
		// undeploy during pre_update
		.and()
			.withExternal()
			.source(FsmStates.PRE_UPDATE_IN_PROGRESS).target(FsmStates.CANCELLATION_REQUESTED)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.requestCancelTask())
		.and()
			.withExternal()
			.source(FsmStates.TASK_CANCELLING).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.PRE_UPDATE_CANCELED)
			.action(actions.undeploy())
		.and()
			.withExternal()
			.source(FsmStates.PRE_UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_IN_PROGRESS)
			.event(FsmEvents.PRE_UPDATE_SUCCESS)
			.action(actions.update())
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_IN_PROGRESS)
			.event(FsmEvents.PRE_UPDATE_SKIPPED)
			.action(actions.update())
		.and()
			.withExternal()
			.source(FsmStates.PRE_UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_FAILED)
			.event(FsmEvents.PRE_UPDATE_FAILURE)
			.action(actions.notifyPrePostUpdateFailure())
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_IN_PROGRESS).target(FsmStates.POST_UPDATE_IN_PROGRESS)
			.event(FsmEvents.UPDATE_SUCCESS)
			.action(actions.postUpdate())
		.and()
			.withExternal()
			.source(FsmStates.POST_UPDATE_IN_PROGRESS).target(FsmStates.UPDATED)
			.event(FsmEvents.POST_UPDATE_SUCCESS)
			.action(actions.notifyUpdateSucces())
		.and()
			.withExternal()
			.source(FsmStates.POST_UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_FAILED)
			.event(FsmEvents.POST_UPDATE_FAILURE)
			.action(actions.notifyPrePostUpdateFailure())
		// The post_update workflow can be cancelled manually
		.and()
			.withExternal()
			.source(FsmStates.POST_UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_FAILED)
			.event(FsmEvents.POST_UPDATE_CANCELED)
			.action(actions.notifyPrePostUpdateFailure())
		// undeploy during post_update
		.and()
			.withExternal()
			.source(FsmStates.POST_UPDATE_IN_PROGRESS).target(FsmStates.CANCELLATION_REQUESTED)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.requestCancelTask())
		.and()
			.withExternal()
			.source(FsmStates.TASK_CANCELLING).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.POST_UPDATE_CANCELED)
			.action(actions.undeploy())
// Failure
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_IN_PROGRESS).target(FsmStates.UPDATE_FAILED)
			.event(FsmEvents.FAILURE)
// Allow undeploy from UPDATED state
		.and()
			.withExternal()
			.source(FsmStates.UPDATED).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.undeploy())
// Allow undeploy from UPDATE_FAILED state
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_FAILED).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.undeploy())

		.and()
			.withExternal()
			.source(FsmStates.DEPLOYED).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.undeploy())
		.and()
				.withExternal()
				.source(FsmStates.UNDEPLOYMENT_FAILED).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
				.event(FsmEvents.UNDEPLOYMENT_STARTED)
				.action(actions.undeploy())
		.and()
				.withExternal()
				.source(FsmStates.UNDEPLOYMENT_FAILED).target(FsmStates.UNDEPLOYMENT_PURGING)
				.event(FsmEvents.PURGE_STARTED)
				.action(actions.syncForcedPurge())
		.and()
				.withExternal()
				.source(FsmStates.UNDEPLOYMENT_FAILED).target(FsmStates.PRE_RESUME_UNDEPLOY)
				.event(FsmEvents.PRE_RESUME)
				.action(actions.preResume())
		.and()
				.withExternal()
				.source(FsmStates.UNDEPLOYMENT_FAILED).target(FsmStates.RESUME_UNDEPLOY)
				.event(FsmEvents.RESUME)
				.action(actions.resume())
		.and()
				.withExternal()
				.source(FsmStates.PRE_RESUME_UNDEPLOY).target(FsmStates.RESUME_UNDEPLOY)
				.event(FsmEvents.RESUME)
				.action(actions.resume())
		.and()
				.withExternal()
				.source(FsmStates.PRE_RESUME_UNDEPLOY).target(FsmStates.UNDEPLOYMENT_FAILED)
				.event(FsmEvents.FAILURE)
				.action(actions.resume())
		.and()
				.withExternal()
				.source(FsmStates.RESUME_UNDEPLOY).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
				.event(FsmEvents.RESUME)
		.and()
				.withExternal()
				.source(FsmStates.RESUME_UNDEPLOY).target(FsmStates.UNDEPLOYMENT_FAILED)
				.event(FsmEvents.FAILURE)
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_IN_PROGRESS).target(FsmStates.CANCELLATION_REQUESTED)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.requestCancelTask())
		.and()
			.withExternal()
			.source(FsmStates.CANCELLATION_REQUESTED).target(FsmStates.TASK_CANCELLING)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.cancelTask())
		.and()
			.withExternal()
			.source(FsmStates.TASK_CANCELLING).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.FAILURE)
			.action(actions.undeploy())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_IN_PROGRESS).target(FsmStates.UNDEPLOYMENT_WAITING_LOGS)
			.event(FsmEvents.UNDEPLOYMENT_SUCCESS)
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_IN_PROGRESS).target(FsmStates.UNDEPLOYMENT_WAITING_EVENTS)
			.event(FsmEvents.LAST_LOG_RECEIVED)
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_WAITING_LOGS).target(FsmStates.UNDEPLOYMENT_PURGING)
			.event(FsmEvents.LAST_LOG_RECEIVED)
			.action(actions.syncPurge())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_WAITING_EVENTS).target(FsmStates.UNDEPLOYMENT_PURGING)
			.event(FsmEvents.UNDEPLOYMENT_SUCCESS)
			.action(actions.syncPurge())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_IN_PROGRESS).target(FsmStates.UNDEPLOYMENT_FAILED)
			.event(FsmEvents.FAILURE)
		.and()
			.withExternal()
			.source(FsmStates.FAILED).target(FsmStates.UNDEPLOYMENT_IN_PROGRESS)
			.event(FsmEvents.UNDEPLOYMENT_STARTED)
			.action(actions.undeploy())
		.and()
			.withExternal()
			.source(FsmStates.FAILED).target(FsmStates.RESUME_DEPLOY)
			.event(FsmEvents.RESUME)
			.action(actions.resume())
		.and()
			.withExternal()
			.source(FsmStates.FAILED).target(FsmStates.PRE_RESUME_DEPLOY)
			.event(FsmEvents.PRE_RESUME)
			.action(actions.preResume())
		.and()
			.withExternal()
			.source(FsmStates.RESUME_DEPLOY).target(FsmStates.FAILED)
			.event(FsmEvents.FAILURE)
		.and()
				.withExternal()
				.source(FsmStates.RESUME_DEPLOY).target(FsmStates.DEPLOYMENT_IN_PROGRESS)
				.event(FsmEvents.RESUME)
		.and()
				.withExternal()
				.source(FsmStates.PRE_RESUME_DEPLOY).target(FsmStates.FAILED)
				.event(FsmEvents.FAILURE)
		.and()
				.withExternal()
				.source(FsmStates.PRE_RESUME_DEPLOY).target(FsmStates.RESUME_DEPLOY)
				.event(FsmEvents.RESUME)
				.action(actions.resume())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_IN_PROGRESS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.DEPLOYMENT_NOT_EXISTING)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_PURGING).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.DEPLOYMENT_PURGED)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_PURGING).target(FsmStates.PURGE_FAILED)
			.event(FsmEvents.FAILURE)
		.and()
			.withExternal()
			.source(FsmStates.PURGE_FAILED).target(FsmStates.UNDEPLOYMENT_PURGING)
			.event(FsmEvents.PURGE_STARTED)
			.action(actions.syncForcedPurge())
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_FAILED).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UPDATED).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UPDATE_IN_PROGRESS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.PRE_UPDATE_IN_PROGRESS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.POST_UPDATE_IN_PROGRESS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYMENT_IN_PROGRESS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.DEPLOYED).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.TASK_CANCELLING).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_IN_PROGRESS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_WAITING_LOGS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_WAITING_EVENTS).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_PURGING).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.UNDEPLOYMENT_FAILED).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.PURGE_FAILED).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
		.and()
			.withExternal()
			.source(FsmStates.FAILED).target(FsmStates.UNDEPLOYED)
			.event(FsmEvents.EVICTION)
			.action(actions.cleanup())
			;
	}

	private void configure(StateMachineConfigurationConfigurer<FsmStates, FsmEvents> config, String id) throws Exception {
		config.withConfiguration().machineId(id).autoStartup(true);
	}
}
