package alien4cloud.paas.yorc.context.service.fsm;

public enum FsmEvents {
    DEPLOYMENT_INIT,
    DEPLOYMENT_STARTED,
    DEPLOYMENT_IN_PROGRESS,
    DEPLOYMENT_SUCCESS,
    UNDEPLOYMENT_STARTED,
    UNDEPLOYMENT_SUCCESS,
    DEPLOYMENT_PURGED,
    DEPLOYMENT_NOT_EXISTING,
    DEPLOYMENT_CONFLICT,
    UPDATE_STARTED,
    UPDATE_IN_PROGRESS,
    UPDATE_SUCCESS,
    POST_UPDATE_IN_PROGRESS,
    POST_UPDATE_SUCCESS,
    POST_UPDATE_FAILURE,
    POST_UPDATE_CANCELED,
    FAILURE,
    EVICTION,
}
