package alien4cloud.paas.yorc.context.service.fsm;

public enum FsmStates {
	UNDEPLOYED, DEPLOYMENT_INIT, DEPLOYMENT_IN_PROGRESS, DEPLOYED, CANCELLATION_REQUESTED, TASK_CANCELLING, UNDEPLOYMENT_IN_PROGRESS, UNDEPLOYMENT_PURGING, FAILED
}
